import { BattleMode, PokemonTypes } from "./Enums"

type PokemonType = {
  [key in PokemonTypes]: {
    [key in BattleMode]: {
      [key in PokemonTypes]: number
    }
  }
}

export const normalMap = {
  [BattleMode.ATTACK]: {
    [PokemonTypes.BUG]: 1,
    [PokemonTypes.DARK]: 1,
    [PokemonTypes.DRAGON]: 1,
    [PokemonTypes.ELECTRIC]: 1,
    [PokemonTypes.FAIRY]: 1,
    [PokemonTypes.FIGHTING]: 1,
    [PokemonTypes.FIRE]: 1,
    [PokemonTypes.FLYING]: 1,
    [PokemonTypes.GHOST]: 0,
    [PokemonTypes.GRASS]: 1,
    [PokemonTypes.GROUND]: 1,
    [PokemonTypes.ICE]: 1,
    [PokemonTypes.NORMAL]: 1,
    [PokemonTypes.POISON]: 1,
    [PokemonTypes.PSYCHIC]: 1,
    [PokemonTypes.ROCK]: 0.5,
    [PokemonTypes.STEEL]: 0.5,
    [PokemonTypes.WATER]: 1,
    [PokemonTypes.NONE]: 1,
  },
  [BattleMode.DEFEND]: {
    [PokemonTypes.BUG]: 1,
    [PokemonTypes.DARK]: 1,
    [PokemonTypes.DRAGON]: 1,
    [PokemonTypes.ELECTRIC]: 1,
    [PokemonTypes.FAIRY]: 1,
    [PokemonTypes.FIGHTING]: 2,
    [PokemonTypes.FIRE]: 1,
    [PokemonTypes.FLYING]: 1,
    [PokemonTypes.GHOST]: 0,
    [PokemonTypes.GRASS]: 1,
    [PokemonTypes.GROUND]: 1,
    [PokemonTypes.ICE]: 1,
    [PokemonTypes.NORMAL]: 1,
    [PokemonTypes.POISON]: 1,
    [PokemonTypes.PSYCHIC]: 1,
    [PokemonTypes.ROCK]: 1,
    [PokemonTypes.STEEL]: 1,
    [PokemonTypes.WATER]: 1,
    [PokemonTypes.NONE]: 1,
  }
}

export const fireMap = {
  [BattleMode.ATTACK]: {
    [PokemonTypes.BUG]: 2,
    [PokemonTypes.DARK]: 1,
    [PokemonTypes.DRAGON]: 0.5,
    [PokemonTypes.ELECTRIC]: 1,
    [PokemonTypes.FAIRY]: 1,
    [PokemonTypes.FIGHTING]: 1,
    [PokemonTypes.FIRE]: 0.5,
    [PokemonTypes.FLYING]: 1,
    [PokemonTypes.GHOST]: 1,
    [PokemonTypes.GRASS]: 2,
    [PokemonTypes.GROUND]: 1,
    [PokemonTypes.ICE]: 2,
    [PokemonTypes.NORMAL]: 1,
    [PokemonTypes.POISON]: 1,
    [PokemonTypes.PSYCHIC]: 1,
    [PokemonTypes.ROCK]: 0.5,
    [PokemonTypes.STEEL]: 2,
    [PokemonTypes.WATER]: 0.5,
    [PokemonTypes.NONE]: 1,
  },
  [BattleMode.DEFEND]: {
    [PokemonTypes.BUG]: 0.5,
    [PokemonTypes.DARK]: 1,
    [PokemonTypes.DRAGON]: 1,
    [PokemonTypes.ELECTRIC]: 1,
    [PokemonTypes.FAIRY]: 0.5,
    [PokemonTypes.FIGHTING]: 1,
    [PokemonTypes.FIRE]: 0.5,
    [PokemonTypes.FLYING]: 1,
    [PokemonTypes.GHOST]: 1,
    [PokemonTypes.GRASS]: 0.5,
    [PokemonTypes.GROUND]: 2,
    [PokemonTypes.ICE]: 0.5,
    [PokemonTypes.NORMAL]: 1,
    [PokemonTypes.POISON]: 1,
    [PokemonTypes.PSYCHIC]: 1,
    [PokemonTypes.ROCK]: 2,
    [PokemonTypes.STEEL]: 0.5,
    [PokemonTypes.WATER]: 2,
    [PokemonTypes.NONE]: 1,
  }
}

export const waterMap = {
  [BattleMode.ATTACK]: {
    [PokemonTypes.BUG]: 1,
    [PokemonTypes.DARK]: 1,
    [PokemonTypes.DRAGON]: 0.5,
    [PokemonTypes.ELECTRIC]: 1,
    [PokemonTypes.FAIRY]: 1,
    [PokemonTypes.FIGHTING]: 1,
    [PokemonTypes.FIRE]: 2,
    [PokemonTypes.FLYING]: 1,
    [PokemonTypes.GHOST]: 1,
    [PokemonTypes.GRASS]: 0.5,
    [PokemonTypes.GROUND]: 2,
    [PokemonTypes.ICE]: 1,
    [PokemonTypes.NORMAL]: 1,
    [PokemonTypes.POISON]: 1,
    [PokemonTypes.PSYCHIC]: 1,
    [PokemonTypes.ROCK]: 2,
    [PokemonTypes.STEEL]: 1,
    [PokemonTypes.WATER]: 0.5,
    [PokemonTypes.NONE]: 1,
  },
  [BattleMode.DEFEND]: {
    [PokemonTypes.BUG]: 1,
    [PokemonTypes.DARK]: 1,
    [PokemonTypes.DRAGON]: 1,
    [PokemonTypes.ELECTRIC]: 2,
    [PokemonTypes.FAIRY]: 1,
    [PokemonTypes.FIGHTING]: 1,
    [PokemonTypes.FIRE]: 0.5,
    [PokemonTypes.FLYING]: 1,
    [PokemonTypes.GHOST]: 1,
    [PokemonTypes.GRASS]: 2,
    [PokemonTypes.GROUND]: 1,
    [PokemonTypes.ICE]: 0.5,
    [PokemonTypes.NORMAL]: 1,
    [PokemonTypes.POISON]: 1,
    [PokemonTypes.PSYCHIC]: 1,
    [PokemonTypes.ROCK]: 1,
    [PokemonTypes.STEEL]: 0.5,
    [PokemonTypes.WATER]: 0.5,
    [PokemonTypes.NONE]: 1,
  }
}

export const grassMap = {
  [BattleMode.ATTACK]: {
    [PokemonTypes.BUG]: 0.5,
    [PokemonTypes.DARK]: 1,
    [PokemonTypes.DRAGON]: 0.5,
    [PokemonTypes.ELECTRIC]: 1,
    [PokemonTypes.FAIRY]: 1,
    [PokemonTypes.FIGHTING]: 1,
    [PokemonTypes.FIRE]: 0.5,
    [PokemonTypes.FLYING]: 0.5,
    [PokemonTypes.GHOST]: 1,
    [PokemonTypes.GRASS]: 0.5,
    [PokemonTypes.GROUND]: 2,
    [PokemonTypes.ICE]: 1,
    [PokemonTypes.NORMAL]: 1,
    [PokemonTypes.POISON]: 0.5,
    [PokemonTypes.PSYCHIC]: 1,
    [PokemonTypes.ROCK]: 2,
    [PokemonTypes.STEEL]: 0.5,
    [PokemonTypes.WATER]: 2,
    [PokemonTypes.NONE]: 1,
  },
  [BattleMode.DEFEND]: {
    [PokemonTypes.BUG]: 2,
    [PokemonTypes.DARK]: 1,
    [PokemonTypes.DRAGON]: 1,
    [PokemonTypes.ELECTRIC]: 0.5,
    [PokemonTypes.FAIRY]: 1,
    [PokemonTypes.FIGHTING]: 1,
    [PokemonTypes.FIRE]: 2,
    [PokemonTypes.FLYING]: 2,
    [PokemonTypes.GHOST]: 1,
    [PokemonTypes.GRASS]: 0.5,
    [PokemonTypes.GROUND]: 0.5,
    [PokemonTypes.ICE]: 2,
    [PokemonTypes.NORMAL]: 1,
    [PokemonTypes.POISON]: 2,
    [PokemonTypes.PSYCHIC]: 1,
    [PokemonTypes.ROCK]: 1,
    [PokemonTypes.STEEL]: 1,
    [PokemonTypes.WATER]: 0.5,
    [PokemonTypes.NONE]: 1,
  }
}

export const electricMap = {
  [BattleMode.ATTACK]: {
    [PokemonTypes.BUG]: 1,
    [PokemonTypes.DARK]: 1,
    [PokemonTypes.DRAGON]: 0.5,
    [PokemonTypes.ELECTRIC]: 0.5,
    [PokemonTypes.FAIRY]: 1,
    [PokemonTypes.FIGHTING]: 1,
    [PokemonTypes.FIRE]: 1,
    [PokemonTypes.FLYING]: 2,
    [PokemonTypes.GHOST]: 1,
    [PokemonTypes.GRASS]: 0.5,
    [PokemonTypes.GROUND]: 0,
    [PokemonTypes.ICE]: 1,
    [PokemonTypes.NORMAL]: 1,
    [PokemonTypes.POISON]: 1,
    [PokemonTypes.PSYCHIC]: 1,
    [PokemonTypes.ROCK]: 1,
    [PokemonTypes.STEEL]: 1,
    [PokemonTypes.WATER]: 2,
    [PokemonTypes.NONE]: 1,
  },
  [BattleMode.DEFEND]: {
    [PokemonTypes.BUG]: 1,
    [PokemonTypes.DARK]: 1,
    [PokemonTypes.DRAGON]: 1,
    [PokemonTypes.ELECTRIC]: 0.5,
    [PokemonTypes.FAIRY]: 1,
    [PokemonTypes.FIGHTING]: 2,
    [PokemonTypes.FIRE]: 1,
    [PokemonTypes.FLYING]: 0.5,
    [PokemonTypes.GHOST]: 1,
    [PokemonTypes.GRASS]: 1,
    [PokemonTypes.GROUND]: 2,
    [PokemonTypes.ICE]: 1,
    [PokemonTypes.NORMAL]: 1,
    [PokemonTypes.POISON]: 1,
    [PokemonTypes.PSYCHIC]: 1,
    [PokemonTypes.ROCK]: 1,
    [PokemonTypes.STEEL]: 0.5,
    [PokemonTypes.WATER]: 1,
    [PokemonTypes.NONE]: 1,
  }
}

export const iceMap = {
  [BattleMode.ATTACK]: {
    [PokemonTypes.BUG]: 1,
    [PokemonTypes.DARK]: 1,
    [PokemonTypes.DRAGON]: 2,
    [PokemonTypes.ELECTRIC]: 1,
    [PokemonTypes.FAIRY]: 1,
    [PokemonTypes.FIGHTING]: 1,
    [PokemonTypes.FIRE]: 0.5,
    [PokemonTypes.FLYING]: 2,
    [PokemonTypes.GHOST]: 1,
    [PokemonTypes.GRASS]: 2,
    [PokemonTypes.GROUND]: 2,
    [PokemonTypes.ICE]: 0.5,
    [PokemonTypes.NORMAL]: 1,
    [PokemonTypes.POISON]: 1,
    [PokemonTypes.PSYCHIC]: 1,
    [PokemonTypes.ROCK]: 1,
    [PokemonTypes.STEEL]: 0.5,
    [PokemonTypes.WATER]: 0.5,
    [PokemonTypes.NONE]: 1,
  },
  [BattleMode.DEFEND]: {
    [PokemonTypes.BUG]: 1,
    [PokemonTypes.DARK]: 1,
    [PokemonTypes.DRAGON]: 1,
    [PokemonTypes.ELECTRIC]: 1,
    [PokemonTypes.FAIRY]: 1,
    [PokemonTypes.FIGHTING]: 2,
    [PokemonTypes.FIRE]: 2,
    [PokemonTypes.FLYING]: 1,
    [PokemonTypes.GHOST]: 1,
    [PokemonTypes.GRASS]: 1,
    [PokemonTypes.GROUND]: 1,
    [PokemonTypes.ICE]: 0.5,
    [PokemonTypes.NORMAL]: 1,
    [PokemonTypes.POISON]: 1,
    [PokemonTypes.PSYCHIC]: 1,
    [PokemonTypes.ROCK]: 2,
    [PokemonTypes.STEEL]: 2,
    [PokemonTypes.WATER]: 1,
    [PokemonTypes.NONE]: 1,
  }
}

export const fightingMap = {
  [BattleMode.ATTACK]: {
    [PokemonTypes.BUG]: 0.5,
    [PokemonTypes.DARK]: 2,
    [PokemonTypes.DRAGON]: 1,
    [PokemonTypes.ELECTRIC]: 1,
    [PokemonTypes.FAIRY]: 0.5,
    [PokemonTypes.FIGHTING]: 1,
    [PokemonTypes.FIRE]: 1,
    [PokemonTypes.FLYING]: 0.5,
    [PokemonTypes.GHOST]: 0,
    [PokemonTypes.GRASS]: 1,
    [PokemonTypes.GROUND]: 1,
    [PokemonTypes.ICE]: 2,
    [PokemonTypes.NORMAL]: 2,
    [PokemonTypes.POISON]: 0.5,
    [PokemonTypes.PSYCHIC]: 0.5,
    [PokemonTypes.ROCK]: 2,
    [PokemonTypes.STEEL]: 2,
    [PokemonTypes.WATER]: 1,
    [PokemonTypes.NONE]: 1,
  },
  [BattleMode.DEFEND]: {
    [PokemonTypes.BUG]: 0.5,
    [PokemonTypes.DARK]: 0.5,
    [PokemonTypes.DRAGON]: 1,
    [PokemonTypes.ELECTRIC]: 1,
    [PokemonTypes.FAIRY]: 2,
    [PokemonTypes.FIGHTING]: 1,
    [PokemonTypes.FIRE]: 1,
    [PokemonTypes.FLYING]: 2,
    [PokemonTypes.GHOST]: 1,
    [PokemonTypes.GRASS]: 1,
    [PokemonTypes.GROUND]: 1,
    [PokemonTypes.ICE]: 1,
    [PokemonTypes.NORMAL]: 1,
    [PokemonTypes.POISON]: 1,
    [PokemonTypes.PSYCHIC]: 2,
    [PokemonTypes.ROCK]: 0.5,
    [PokemonTypes.STEEL]: 1,
    [PokemonTypes.WATER]: 1,
    [PokemonTypes.NONE]: 1,
  }
}

export const poisonMap = {
  [BattleMode.ATTACK]: {
    [PokemonTypes.BUG]: 1,
    [PokemonTypes.DARK]: 1,
    [PokemonTypes.DRAGON]: 1,
    [PokemonTypes.ELECTRIC]: 1,
    [PokemonTypes.FAIRY]: 2,
    [PokemonTypes.FIGHTING]: 1,
    [PokemonTypes.FIRE]: 1,
    [PokemonTypes.FLYING]: 1,
    [PokemonTypes.GHOST]: 0.5,
    [PokemonTypes.GRASS]: 2,
    [PokemonTypes.GROUND]: 0.5,
    [PokemonTypes.ICE]: 1,
    [PokemonTypes.NORMAL]: 1,
    [PokemonTypes.POISON]: 0.5,
    [PokemonTypes.PSYCHIC]: 1,
    [PokemonTypes.ROCK]: 0.5,
    [PokemonTypes.STEEL]: 0,
    [PokemonTypes.WATER]: 1,
    [PokemonTypes.NONE]: 1,
  },
  [BattleMode.DEFEND]: {
    [PokemonTypes.BUG]: 0.5,
    [PokemonTypes.DARK]: 1,
    [PokemonTypes.DRAGON]: 1,
    [PokemonTypes.ELECTRIC]: 1,
    [PokemonTypes.FAIRY]: 1,
    [PokemonTypes.FIGHTING]: 0.5,
    [PokemonTypes.FIRE]: 1,
    [PokemonTypes.FLYING]: 1,
    [PokemonTypes.GHOST]: 1,
    [PokemonTypes.GRASS]: 0.5,
    [PokemonTypes.GROUND]: 2,
    [PokemonTypes.ICE]: 1,
    [PokemonTypes.NORMAL]: 1,
    [PokemonTypes.POISON]: 0.5,
    [PokemonTypes.PSYCHIC]: 2,
    [PokemonTypes.ROCK]: 1,
    [PokemonTypes.STEEL]: 1,
    [PokemonTypes.WATER]: 1,
    [PokemonTypes.NONE]: 1,
  }
}

export const groundMap = {
  [BattleMode.ATTACK]: {
    [PokemonTypes.BUG]: 0.5,
    [PokemonTypes.DARK]: 1,
    [PokemonTypes.DRAGON]: 1,
    [PokemonTypes.ELECTRIC]: 2,
    [PokemonTypes.FAIRY]: 1,
    [PokemonTypes.FIGHTING]: 1,
    [PokemonTypes.FIRE]: 2,
    [PokemonTypes.FLYING]: 0,
    [PokemonTypes.GHOST]: 1,
    [PokemonTypes.GRASS]: 0.5,
    [PokemonTypes.GROUND]: 1,
    [PokemonTypes.ICE]: 1,
    [PokemonTypes.NORMAL]: 1,
    [PokemonTypes.POISON]: 2,
    [PokemonTypes.PSYCHIC]: 1,
    [PokemonTypes.ROCK]: 2,
    [PokemonTypes.STEEL]: 2,
    [PokemonTypes.WATER]: 1,
    [PokemonTypes.NONE]: 1,
  },
  [BattleMode.DEFEND]: {
    [PokemonTypes.BUG]: 1,
    [PokemonTypes.DARK]: 1,
    [PokemonTypes.DRAGON]: 1,
    [PokemonTypes.ELECTRIC]: 0,
    [PokemonTypes.FAIRY]: 1,
    [PokemonTypes.FIGHTING]: 1,
    [PokemonTypes.FIRE]: 1,
    [PokemonTypes.FLYING]: 1,
    [PokemonTypes.GHOST]: 1,
    [PokemonTypes.GRASS]: 2,
    [PokemonTypes.GROUND]: 1,
    [PokemonTypes.ICE]: 2,
    [PokemonTypes.NORMAL]: 1,
    [PokemonTypes.POISON]: 1,
    [PokemonTypes.PSYCHIC]: 1,
    [PokemonTypes.ROCK]: 1,
    [PokemonTypes.STEEL]: 1,
    [PokemonTypes.WATER]: 2,
    [PokemonTypes.NONE]: 1,
  }
}

export const flyingMap = {
  [BattleMode.ATTACK]: {
    [PokemonTypes.BUG]: 2,
    [PokemonTypes.DARK]: 1,
    [PokemonTypes.DRAGON]: 1,
    [PokemonTypes.ELECTRIC]: 0.5,
    [PokemonTypes.FAIRY]: 1,
    [PokemonTypes.FIGHTING]: 2,
    [PokemonTypes.FIRE]: 1,
    [PokemonTypes.FLYING]: 1,
    [PokemonTypes.GHOST]: 1,
    [PokemonTypes.GRASS]: 2,
    [PokemonTypes.GROUND]: 1,
    [PokemonTypes.ICE]: 1,
    [PokemonTypes.NORMAL]: 1,
    [PokemonTypes.POISON]: 1,
    [PokemonTypes.PSYCHIC]: 1,
    [PokemonTypes.ROCK]: 0.5,
    [PokemonTypes.STEEL]: 0.5,
    [PokemonTypes.WATER]: 1,
    [PokemonTypes.NONE]: 1,
  },
  [BattleMode.DEFEND]: {
    [PokemonTypes.BUG]: 0.5,
    [PokemonTypes.DARK]: 1,
    [PokemonTypes.DRAGON]: 1,
    [PokemonTypes.ELECTRIC]: 2,
    [PokemonTypes.FAIRY]: 1,
    [PokemonTypes.FIGHTING]: 0.5,
    [PokemonTypes.FIRE]: 1,
    [PokemonTypes.FLYING]: 1,
    [PokemonTypes.GHOST]: 1,
    [PokemonTypes.GRASS]: 0.5,
    [PokemonTypes.GROUND]: 0,
    [PokemonTypes.ICE]: 2,
    [PokemonTypes.NORMAL]: 1,
    [PokemonTypes.POISON]: 1,
    [PokemonTypes.PSYCHIC]: 1,
    [PokemonTypes.ROCK]: 2,
    [PokemonTypes.STEEL]: 1,
    [PokemonTypes.WATER]: 1,
    [PokemonTypes.NONE]: 1,
  }
}

export const psychicMap = {
  [BattleMode.ATTACK]: {
    [PokemonTypes.BUG]: 1,
    [PokemonTypes.DARK]: 0,
    [PokemonTypes.DRAGON]: 1,
    [PokemonTypes.ELECTRIC]: 1,
    [PokemonTypes.FAIRY]: 1,
    [PokemonTypes.FIGHTING]: 2,
    [PokemonTypes.FIRE]: 1,
    [PokemonTypes.FLYING]: 1,
    [PokemonTypes.GHOST]: 1,
    [PokemonTypes.GRASS]: 1,
    [PokemonTypes.GROUND]: 1,
    [PokemonTypes.ICE]: 1,
    [PokemonTypes.NORMAL]: 1,
    [PokemonTypes.POISON]: 2,
    [PokemonTypes.PSYCHIC]: 0.5,
    [PokemonTypes.ROCK]: 1,
    [PokemonTypes.STEEL]: 0.5,
    [PokemonTypes.WATER]: 1,
    [PokemonTypes.NONE]: 1,
  },
  [BattleMode.DEFEND]: {
    [PokemonTypes.BUG]: 2,
    [PokemonTypes.DARK]: 2,
    [PokemonTypes.DRAGON]: 1,
    [PokemonTypes.ELECTRIC]: 1,
    [PokemonTypes.FAIRY]: 1,
    [PokemonTypes.FIGHTING]: 0.5,
    [PokemonTypes.FIRE]: 1,
    [PokemonTypes.FLYING]: 1,
    [PokemonTypes.GHOST]: 2,
    [PokemonTypes.GRASS]: 1,
    [PokemonTypes.GROUND]: 1,
    [PokemonTypes.ICE]: 1,
    [PokemonTypes.NORMAL]: 1,
    [PokemonTypes.POISON]: 1,
    [PokemonTypes.PSYCHIC]: 0.5,
    [PokemonTypes.ROCK]: 1,
    [PokemonTypes.STEEL]: 1,
    [PokemonTypes.WATER]: 1,
    [PokemonTypes.NONE]: 1,
  }
}

export const bugMap = {
  [BattleMode.ATTACK]: {
    [PokemonTypes.BUG]: 1,
    [PokemonTypes.DARK]: 2,
    [PokemonTypes.DRAGON]: 1,
    [PokemonTypes.ELECTRIC]: 1,
    [PokemonTypes.FAIRY]: 0.5,
    [PokemonTypes.FIGHTING]: 0.5,
    [PokemonTypes.FIRE]: 0.5,
    [PokemonTypes.FLYING]: 0.5,
    [PokemonTypes.GHOST]: 0.5,
    [PokemonTypes.GRASS]: 2,
    [PokemonTypes.GROUND]: 1,
    [PokemonTypes.ICE]: 1,
    [PokemonTypes.NORMAL]: 1,
    [PokemonTypes.POISON]: 0.5,
    [PokemonTypes.PSYCHIC]: 2,
    [PokemonTypes.ROCK]: 1,
    [PokemonTypes.STEEL]: 0.5,
    [PokemonTypes.WATER]: 1,
    [PokemonTypes.NONE]: 1,
  },
  [BattleMode.DEFEND]: {
    [PokemonTypes.BUG]: 1,
    [PokemonTypes.DARK]: 1,
    [PokemonTypes.DRAGON]: 1,
    [PokemonTypes.ELECTRIC]: 1,
    [PokemonTypes.FAIRY]: 1,
    [PokemonTypes.FIGHTING]: 0.5,
    [PokemonTypes.FIRE]: 2,
    [PokemonTypes.FLYING]: 2,
    [PokemonTypes.GHOST]: 1,
    [PokemonTypes.GRASS]: 0.5,
    [PokemonTypes.GROUND]: 0.5,
    [PokemonTypes.ICE]: 1,
    [PokemonTypes.NORMAL]: 1,
    [PokemonTypes.POISON]: 1,
    [PokemonTypes.PSYCHIC]: 1,
    [PokemonTypes.ROCK]: 2,
    [PokemonTypes.STEEL]: 1,
    [PokemonTypes.WATER]: 1,
    [PokemonTypes.NONE]: 1,
  }
}

export const rockMap = {
  [BattleMode.ATTACK]: {
    [PokemonTypes.BUG]: 2,
    [PokemonTypes.DARK]: 1,
    [PokemonTypes.DRAGON]: 1,
    [PokemonTypes.ELECTRIC]: 1,
    [PokemonTypes.FAIRY]: 1,
    [PokemonTypes.FIGHTING]: 0.5,
    [PokemonTypes.FIRE]: 2,
    [PokemonTypes.FLYING]: 2,
    [PokemonTypes.GHOST]: 1,
    [PokemonTypes.GRASS]: 1,
    [PokemonTypes.GROUND]: 0.5,
    [PokemonTypes.ICE]: 2,
    [PokemonTypes.NORMAL]: 1,
    [PokemonTypes.POISON]: 1,
    [PokemonTypes.PSYCHIC]: 1,
    [PokemonTypes.ROCK]: 1,
    [PokemonTypes.STEEL]: 0.5,
    [PokemonTypes.WATER]: 1,
    [PokemonTypes.NONE]: 1,
  },
  [BattleMode.DEFEND]: {
    [PokemonTypes.BUG]: 1,
    [PokemonTypes.DARK]: 1,
    [PokemonTypes.DRAGON]: 1,
    [PokemonTypes.ELECTRIC]: 1,
    [PokemonTypes.FAIRY]: 1,
    [PokemonTypes.FIGHTING]: 2,
    [PokemonTypes.FIRE]: 0.5,
    [PokemonTypes.FLYING]: 0.5,
    [PokemonTypes.GHOST]: 1,
    [PokemonTypes.GRASS]: 2,
    [PokemonTypes.GROUND]: 2,
    [PokemonTypes.ICE]: 1,
    [PokemonTypes.NORMAL]: 0.5,
    [PokemonTypes.POISON]: 0.5,
    [PokemonTypes.PSYCHIC]: 1,
    [PokemonTypes.ROCK]: 1,
    [PokemonTypes.STEEL]: 2,
    [PokemonTypes.WATER]: 2,
    [PokemonTypes.NONE]: 1,
  }
}

export const ghostMap = {
  [BattleMode.ATTACK]: {
    [PokemonTypes.BUG]: 1,
    [PokemonTypes.DARK]: 0.5,
    [PokemonTypes.DRAGON]: 1,
    [PokemonTypes.ELECTRIC]: 1,
    [PokemonTypes.FAIRY]: 1,
    [PokemonTypes.FIGHTING]: 1,
    [PokemonTypes.FIRE]: 1,
    [PokemonTypes.FLYING]: 1,
    [PokemonTypes.GHOST]: 2,
    [PokemonTypes.GRASS]: 1,
    [PokemonTypes.GROUND]: 1,
    [PokemonTypes.ICE]: 1,
    [PokemonTypes.NORMAL]: 0,
    [PokemonTypes.POISON]: 1,
    [PokemonTypes.PSYCHIC]: 2,
    [PokemonTypes.ROCK]: 1,
    [PokemonTypes.STEEL]: 1,
    [PokemonTypes.WATER]: 1,
    [PokemonTypes.NONE]: 1,
  },
  [BattleMode.DEFEND]: {
    [PokemonTypes.BUG]: 0.5,
    [PokemonTypes.DARK]: 2,
    [PokemonTypes.DRAGON]: 1,
    [PokemonTypes.ELECTRIC]: 1,
    [PokemonTypes.FAIRY]: 1,
    [PokemonTypes.FIGHTING]: 0,
    [PokemonTypes.FIRE]: 1,
    [PokemonTypes.FLYING]: 1,
    [PokemonTypes.GHOST]: 2,
    [PokemonTypes.GRASS]: 1,
    [PokemonTypes.GROUND]: 1,
    [PokemonTypes.ICE]: 1,
    [PokemonTypes.NORMAL]: 0,
    [PokemonTypes.POISON]: 0.5,
    [PokemonTypes.PSYCHIC]: 1,
    [PokemonTypes.ROCK]: 1,
    [PokemonTypes.STEEL]: 1,
    [PokemonTypes.WATER]: 1,
    [PokemonTypes.NONE]: 1,
  }
}

export const dragonMap = {
  [BattleMode.ATTACK]: {
    [PokemonTypes.BUG]: 1,
    [PokemonTypes.DARK]: 1,
    [PokemonTypes.DRAGON]: 2,
    [PokemonTypes.ELECTRIC]: 1,
    [PokemonTypes.FAIRY]: 0,
    [PokemonTypes.FIGHTING]: 1,
    [PokemonTypes.FIRE]: 1,
    [PokemonTypes.FLYING]: 1,
    [PokemonTypes.GHOST]: 1,
    [PokemonTypes.GRASS]: 1,
    [PokemonTypes.GROUND]: 1,
    [PokemonTypes.ICE]: 1,
    [PokemonTypes.NORMAL]: 1,
    [PokemonTypes.POISON]: 1,
    [PokemonTypes.PSYCHIC]: 1,
    [PokemonTypes.ROCK]: 1,
    [PokemonTypes.STEEL]: 0.5,
    [PokemonTypes.WATER]: 1,
    [PokemonTypes.NONE]: 1,
  },
  [BattleMode.DEFEND]: {
    [PokemonTypes.BUG]: 1,
    [PokemonTypes.DARK]: 1,
    [PokemonTypes.DRAGON]: 1,
    [PokemonTypes.ELECTRIC]: 0.5,
    [PokemonTypes.FAIRY]: 2,
    [PokemonTypes.FIGHTING]: 2,
    [PokemonTypes.FIRE]: 0.5,
    [PokemonTypes.FLYING]: 1,
    [PokemonTypes.GHOST]: 1,
    [PokemonTypes.GRASS]: 0.5,
    [PokemonTypes.GROUND]: 1,
    [PokemonTypes.ICE]: 2,
    [PokemonTypes.NORMAL]: 1,
    [PokemonTypes.POISON]: 1,
    [PokemonTypes.PSYCHIC]: 1,
    [PokemonTypes.ROCK]: 1,
    [PokemonTypes.STEEL]: 1,
    [PokemonTypes.WATER]: 0.5,
    [PokemonTypes.NONE]: 1,
  }
}

export const darkMap = {
  [BattleMode.ATTACK]: {
    [PokemonTypes.BUG]: 1,
    [PokemonTypes.DARK]: 0.5,
    [PokemonTypes.DRAGON]: 1,
    [PokemonTypes.ELECTRIC]: 1,
    [PokemonTypes.FAIRY]: 0.5,
    [PokemonTypes.FIGHTING]: 0.5,
    [PokemonTypes.FIRE]: 1,
    [PokemonTypes.FLYING]: 1,
    [PokemonTypes.GHOST]: 2,
    [PokemonTypes.GRASS]: 1,
    [PokemonTypes.GROUND]: 1,
    [PokemonTypes.ICE]: 1,
    [PokemonTypes.NORMAL]: 1,
    [PokemonTypes.POISON]: 1,
    [PokemonTypes.PSYCHIC]: 2,
    [PokemonTypes.ROCK]: 1,
    [PokemonTypes.STEEL]: 1,
    [PokemonTypes.WATER]: 1,
    [PokemonTypes.NONE]: 1,
  },
  [BattleMode.DEFEND]: {
    [PokemonTypes.BUG]: 2,
    [PokemonTypes.DARK]: 0.5,
    [PokemonTypes.DRAGON]: 1,
    [PokemonTypes.ELECTRIC]: 1,
    [PokemonTypes.FAIRY]: 2,
    [PokemonTypes.FIGHTING]: 2,
    [PokemonTypes.FIRE]: 1,
    [PokemonTypes.FLYING]: 1,
    [PokemonTypes.GHOST]: 0.5,
    [PokemonTypes.GRASS]: 1,
    [PokemonTypes.GROUND]: 1,
    [PokemonTypes.ICE]: 1,
    [PokemonTypes.NORMAL]: 1,
    [PokemonTypes.POISON]: 1,
    [PokemonTypes.PSYCHIC]: 0,
    [PokemonTypes.ROCK]: 1,
    [PokemonTypes.STEEL]: 1,
    [PokemonTypes.WATER]: 1,
    [PokemonTypes.NONE]: 1,
  }
}

export const steelMap = {
  [BattleMode.ATTACK]: {
    [PokemonTypes.BUG]: 1,
    [PokemonTypes.DARK]: 1,
    [PokemonTypes.DRAGON]: 1,
    [PokemonTypes.ELECTRIC]: 0.5,
    [PokemonTypes.FAIRY]: 2,
    [PokemonTypes.FIGHTING]: 1,
    [PokemonTypes.FIRE]: 0.5,
    [PokemonTypes.FLYING]: 1,
    [PokemonTypes.GHOST]: 1,
    [PokemonTypes.GRASS]: 1,
    [PokemonTypes.GROUND]: 1,
    [PokemonTypes.ICE]: 2,
    [PokemonTypes.NORMAL]: 1,
    [PokemonTypes.POISON]: 1,
    [PokemonTypes.PSYCHIC]: 1,
    [PokemonTypes.ROCK]: 2,
    [PokemonTypes.STEEL]: 0.5,
    [PokemonTypes.WATER]: 0.5,
    [PokemonTypes.NONE]: 1,
  },
  [BattleMode.DEFEND]: {
    [PokemonTypes.BUG]: 0.5,
    [PokemonTypes.DARK]: 1,
    [PokemonTypes.DRAGON]: 0.5,
    [PokemonTypes.ELECTRIC]: 1,
    [PokemonTypes.FAIRY]: 0.5,
    [PokemonTypes.FIGHTING]: 2,
    [PokemonTypes.FIRE]: 2,
    [PokemonTypes.FLYING]: 0.5,
    [PokemonTypes.GHOST]: 1,
    [PokemonTypes.GRASS]: 0.5,
    [PokemonTypes.GROUND]: 2,
    [PokemonTypes.ICE]: 0.5,
    [PokemonTypes.NORMAL]: 0.5,
    [PokemonTypes.POISON]: 0,
    [PokemonTypes.PSYCHIC]: 0.5,
    [PokemonTypes.ROCK]: 0.5,
    [PokemonTypes.STEEL]: 0.5,
    [PokemonTypes.WATER]: 1,
    [PokemonTypes.NONE]: 1,
  }
}

export const fairyMap = {
  [BattleMode.ATTACK]: {
    [PokemonTypes.BUG]: 1,
    [PokemonTypes.DARK]: 2,
    [PokemonTypes.DRAGON]: 2,
    [PokemonTypes.ELECTRIC]: 1,
    [PokemonTypes.FAIRY]: 1,
    [PokemonTypes.FIGHTING]: 2,
    [PokemonTypes.FIRE]: 0.5,
    [PokemonTypes.FLYING]: 1,
    [PokemonTypes.GHOST]: 1,
    [PokemonTypes.GRASS]: 1,
    [PokemonTypes.GROUND]: 1,
    [PokemonTypes.ICE]: 1,
    [PokemonTypes.NORMAL]: 1,
    [PokemonTypes.POISON]: 0.5,
    [PokemonTypes.PSYCHIC]: 1,
    [PokemonTypes.ROCK]: 1,
    [PokemonTypes.STEEL]: 0.5,
    [PokemonTypes.WATER]: 1,
    [PokemonTypes.NONE]: 1,
  },
  [BattleMode.DEFEND]: {
    [PokemonTypes.BUG]: 0.5,
    [PokemonTypes.DARK]: 0.5,
    [PokemonTypes.DRAGON]: 0,
    [PokemonTypes.ELECTRIC]: 1,
    [PokemonTypes.FAIRY]: 1,
    [PokemonTypes.FIGHTING]: 0.5,
    [PokemonTypes.FIRE]: 1,
    [PokemonTypes.FLYING]: 1,
    [PokemonTypes.GHOST]: 1,
    [PokemonTypes.GRASS]: 1,
    [PokemonTypes.GROUND]: 1,
    [PokemonTypes.ICE]: 1,
    [PokemonTypes.NORMAL]: 1,
    [PokemonTypes.POISON]: 2,
    [PokemonTypes.PSYCHIC]: 1,
    [PokemonTypes.ROCK]: 1,
    [PokemonTypes.STEEL]: 2,
    [PokemonTypes.WATER]: 1,
    [PokemonTypes.NONE]: 1,
  }
}

export const noneMap = {
  [BattleMode.ATTACK]: {
    [PokemonTypes.BUG]: 1,
    [PokemonTypes.DARK]: 1,
    [PokemonTypes.DRAGON]: 1,
    [PokemonTypes.ELECTRIC]: 1,
    [PokemonTypes.FAIRY]: 1,
    [PokemonTypes.FIGHTING]: 1,
    [PokemonTypes.FIRE]: 1,
    [PokemonTypes.FLYING]: 1,
    [PokemonTypes.GHOST]: 1,
    [PokemonTypes.GRASS]: 1,
    [PokemonTypes.GROUND]: 1,
    [PokemonTypes.ICE]: 1,
    [PokemonTypes.NORMAL]: 1,
    [PokemonTypes.POISON]: 1,
    [PokemonTypes.PSYCHIC]: 1,
    [PokemonTypes.ROCK]: 1,
    [PokemonTypes.STEEL]: 1,
    [PokemonTypes.WATER]: 1,
    [PokemonTypes.NONE]: 1,
  },
  [BattleMode.DEFEND]: {
    [PokemonTypes.BUG]: 1,
    [PokemonTypes.DARK]: 1,
    [PokemonTypes.DRAGON]: 1,
    [PokemonTypes.ELECTRIC]: 1,
    [PokemonTypes.FAIRY]: 1,
    [PokemonTypes.FIGHTING]: 1,
    [PokemonTypes.FIRE]: 1,
    [PokemonTypes.FLYING]: 1,
    [PokemonTypes.GHOST]: 1,
    [PokemonTypes.GRASS]: 1,
    [PokemonTypes.GROUND]: 1,
    [PokemonTypes.ICE]: 1,
    [PokemonTypes.NORMAL]: 1,
    [PokemonTypes.POISON]: 1,
    [PokemonTypes.PSYCHIC]: 1,
    [PokemonTypes.ROCK]: 1,
    [PokemonTypes.STEEL]: 1,
    [PokemonTypes.WATER]: 1,
    [PokemonTypes.NONE]: 1,
  }
}

export const TYPECHART: PokemonType = {
  [PokemonTypes.NORMAL]: normalMap,
  [PokemonTypes.FIRE]: fireMap,
  [PokemonTypes.WATER]: waterMap,
  [PokemonTypes.GRASS]: grassMap,
  [PokemonTypes.ELECTRIC]: electricMap,
  [PokemonTypes.FLYING]: flyingMap,
  [PokemonTypes.GROUND]: groundMap,
  [PokemonTypes.ROCK]: rockMap,
  [PokemonTypes.FIGHTING]: fightingMap,
  [PokemonTypes.ICE]: iceMap,
  [PokemonTypes.POISON]: poisonMap,
  [PokemonTypes.BUG]: bugMap,
  [PokemonTypes.GHOST]: ghostMap,
  [PokemonTypes.PSYCHIC]: psychicMap,
  [PokemonTypes.DRAGON]: dragonMap,
  [PokemonTypes.DARK]: darkMap,
  [PokemonTypes.STEEL]: steelMap,
  [PokemonTypes.FAIRY]: fairyMap,
  [PokemonTypes.NONE]: noneMap,
}